
attitudinal_tag_list <- c(
  "A01_1",
  "A01_2",
  "A01_3",
  "A01_4",
  "A01_6",
  "A02_1",
  "A02_2",
  "A02_3",
  "A02_4",
  "A03_1",
  "A03_2",
  "A03_3",
  "A03_4",
  "A04_1",
  "A04_2",
  "A04_3",
  "A04_4",
  "A04_5",
  "A05_1",
  "A05_2",
  "A05_3",
  "A05_5",
  "A05_6",
  "A06_1",
  "A06_2",
  "A06_3",
  "A06_4"
  # "A06_5",
  # "C11_1",
  # "C11_2",
  # "C11_3",
  # "C11_4",
  # "C11_5",
  # "C11_6",
  # "C11_7",
  # "C11_8",
  # "C11_9",
  # "C11_10",
  # "C11_11",
  # "C11_12",
  # "C11_13",
  # "C11_14",
  # "C11_15",
  # "C11_16",
  # "C11_17",
  # "C11_18",
  # "G07_1",
  # "G07_2",
  # "G07_3",
  # "G07_4",
  # "G07_5",
  # "G07_7",
  # "G07_8",
  # "G07_9",
  # "G07_10",
  # "G07_11",
  # "G08_1",
  # "G08_2",
  # "G08_3",
  # "G08_4"
)

attitudinal_tag_list_long <- c(
  "a1a_like_new_things",
  "a1b_schedule_impossible_pt",
  "a1c_like_walking",
  "a1d_want_own_car",
  "a1e_exercise_important",
  "a1f_raise_gas_price_for_environment",
  "a1g_like_driving",
  "a1h_reduce_impact_environment",
  "a1i_congestion_problem",
  "a1k_fine_rent_car",
  "a1l_like_bike",
  "a1m_prefer_spacious_home",
  "a1n_car_as_just_a_way_to_move",
  "a1o_rightofway_cars",
  "a1p_prefer_being_driver",
  "a1q_no_alternative_to_driving",
  "a1r_like_idea_pt_as_transportation",
  "a1s_like_latest_technology",
  "a1t_reschedule_avoid_congestion",
  "a1u_satified_transpo",
  "a1v_mixed_land_use_neighborhood",
  "a1x_wifi_essential",
  "a1y_pay_quickier_trip",
  "a1z_stretch_budget_for_new_things",
  "a1aa_increase_cost_pt",
  "a1ab_protected_bike",
  "a1ac_costly_parking"
  # "a1ad_satisfied_life",
  # "C11_1",
  # "C11_2",
  # "C11_3",
  # "C11_4",
  # "C11_5",
  # "C11_6",
  # "C11_7",
  # "C11_8",
  # "C11_9",
  # "C11_10",
  # "C11_11",
  # "C11_12",
  # "C11_13",
  # "C11_14",
  # "C11_15",
  # "C11_16",
  # "C11_17",
  # "C11_18",
  # "G07_1",
  # "G07_2",
  # "G07_3",
  # "G07_4",
  # "G07_5",
  # "G07_7",
  # "G07_8",
  # "G07_9",
  # "G07_10",
  # "G07_11",
  # "G08_1",
  # "G08_2",
  # "G08_3",
  # "G08_4"
)

attitudinal_text_list <- c(
  "I like trying things that are new and different.",
  "My schedule makes it hard or impossible for me to use public transportation.",
  "I like walking.",
  "I definitely want to own a car.",
  "Getting regular exercise is very important to me.",
  "We should raise the cost of driving to reduce the negative impacts of transportation on the environment.",
  "I like driving a car.",
  "I always think about ways in which I can reduce my impact on the environment.",
  "Traffic congestion is a major problem in the region where I live.",
  "I am fine with not owning a car, as long as I can use/rent one any time I need it.",
  "I like riding a bike.",
  "I prefer to live in a spacious home, even if it is farther from public transportation and many places I go.",
  "To me, a car is just a way to get from place to place.",
  "I am against giving more space to pedestrians and cyclists on the road network if it implies less space for cars.",
  "I prefer to be a driver rather than a passenger.",
  "Most of the time, I have no reasonable alternative to driving.",
  "I like the idea of public transit as a means of transportation for me.",
  "I like to be among the first people to have the latest technology.",
  "I make efforts to adjust my schedule (e.g., leave earlier/later than needed) to avoid traffic congestion.",
  "I am generally satisfied with my transportation options.",
  "I like the idea of having stores, restaurants, and offices mixed among the homes in my neighborhood.",
  "Having Wi-Fi and/or good internet access on my mobile phone everywhere I go is essential to me.",
  "I am willing to pay more money to have a quicker trip.",
  "I'll stretch my budget to buy something new and exciting.",
  "We should raise the price of driving to provide funding for better public transportation.",
  "If I felt protected from car traffic, I would ride a bicycle more often.",
  "I am less likely to drive if parking is difficult or expensive."
  # "I am generally satisfied with my life.",
  # "I perform better when I interact with colleagues in person.",
  # "I am concerned about the health impacts of the COVID-19 pandemic in my country.",
  # "Working from home makes me less disciplined/self-controlled.",
  # "Now that a COVID-19 vaccine is available/accessible to the general population, I have relaxed my personal precautions (e.g., social distancing, reducing travel).",
  # "Working from home helps me spend more meaningful time with other members of my household.",
  # "I am concerned about the economic impacts of the COVID-19 pandemic in my country.",
  # "I experience substantial gains in efficiency when working from home.",
  # "We should raise taxes to provide health insurance for all.",
  # "Working from home helps me save large costs on commuting and parking.",
  # "The quality of interaction during online meetings is disappointing.",
  # "Working from home is not practical for me (e.g., due to lack of office devices, distractions from family members).",
  # "I am satisfied with the online shopping  and grocery delivery options available to me.",
  # "I can efficiently replace some of my business trips with virtual meetings.",
  # "I am now able to maintain more meaningful contact with friends and family outside of my household by virtual means.",
  # "I enjoy no longer having to physically commute to work.",
  # "I live on a tighter budget now than before the pandemic.",
  # "I enjoy shopping online.",
  # "I prefer to shop in a store rather than online.",
  # "Using bikesharing/e-scooter sharing is fun.",
  # "The lack of a child safety seat and/or equipment to accommodate disabilities prevents me from using ridehailing services.",
  # "I would be more likely to use transportation modes other than driving a car if I could pay for all my transportation needs in one place.",
  # "If ridehailing services disappeared from my city/region, I would need to purchase an additional car.",
  # "If shared bikes and/or e-scooters were cheaper, I would use them more often.",
  # "I would be interested in purchasing a monthly pass that included transit and bikesharing/e-scooter sharing.",
  # "I am interested in monthly rentals of bikes and/or e-scooters that include maintenance and theft protection.",
  # "I am willing to live without a car if I have good access to viable alternatives such as carsharing and ridehailing.",
  # "I feel uncomfortable using public transportation due to concerns about pathogens (e.g., COVID-19 or other).",
  # "I feel uncomfortable putting my hands on the handlebar of a shared e-bike, e-scooter, e-moped recently used by someone else.",
  # "I will travel more by car than I did before the pandemic.",
  # "I will be OK renting out my car to strangers",
  # "I will use ridehailing (e.g., UberX or Lyft) as often as I did before the pandemic.",
  # "I will feel uncomfortable sharing a ride with strangers (e.g., on UberPOOL, Lyft Share) due to concerns about pathogens (e.g., COVID-19 or other)."
)

sociodemographics_tag_list <- c(
  "B01_1",
  "B05",
  "B06",
  "B07",
  "B08",
  "B12",
  "B13_1"
)

sociodemographics_tag_list_long <- c(
  "b01_yearborn",
  "b05_gender",
  "b06_age_driver_license",
  "b07_educational_background",
  "b08_hh_income",
  "b12_interest_in_vaccines",
  "b13_smartphone_dv"
)

remotework_tag_list <- c(
  "C06_1",
  "C07_1",
  "C08_1",
  "C06_3",
  "C07_3",
  "C08_3"
)

remotework_tag_list_long <- c(
  "c06a_work_location_primary_precovid",
  "c07a_work_location_primary_2021",
  "c08a_work_location_primary_2022",
  "c06c_work_location_home_precovid",
  "c07c_work_location_home_2021",
  "c08c_work_location_home_2022"
)

support_info_tag_list <- c(
  "C02_1_1",
  "C02_1_2",
  "C02_1_3",
  "D03"
)

support_info_tag_list_long <- c(
  "c02_work_full_precovid_dv",
  "c02_work_full_2021_dv",
  "c02_work_full_2022_dv",
  "d03_neighborhood_type"
)

tag_list <- c(
  sociodemographics_tag_list,
  attitudinal_tag_list,
  remotework_tag_list,
  support_info_tag_list
)

tag_list_long <- c(
  sociodemographics_tag_list_long,
  attitudinal_tag_list_long,
  remotework_tag_list_long,
  support_info_tag_list_long
)
